---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-v1
  labels:
    app: hello
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
      version: v1
  template:
    metadata:
      labels:
        app: hello
        version: v1
    spec:
      containers:
        - name: hello-v1
          image: ikubernetes/myapp:v1
          ports:
            - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: hello-v1
spec:
  selector:
    app: hello
    version: v1
  ports:
    - port: 80
      targetPort: 80
