---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-v2
  labels:
    app: hello
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
      version: v2
  template:
    metadata:
      labels:
        app: hello
        version: v2
    spec:
      containers:
      - name: hello-v2
        image: ironcore864/go-hello-http:v2
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: hello-v2
spec:
  selector:
    app: hello
    version: v2
  ports:
    - port: 80
      targetPort: 8080
