=== Create cluster in gcp

** Manually create gke cluster and rename cluster name as east, west
*** enable access for two cluster like
----
gcloud container clusters get-credentials devops3 --zone us-central1-c --project fr-dev-piiworker
----

*** rename
----
kubectl config rename-context gke_fr-dev-piiworker_us-central1-c_devops-2 east
kubectl config rename-context gke_fr-dev-piiworker_us-central1-c_devops3 west
----

**** We like to use the step CLI to generate these certificates. If you prefer openssl instead, feel free to use that! To generate the trust anchor with step
**** install step first
----
wget -O step-cli.tar.gz https://github.com/smallstep/cli/releases/download/v0.15.3/step_linux_0.15.3_amd64.tar.gz
tar -xf step-cli.tar.gz
sudo cp step_0.15.3/bin/step /usr/bin
----

**** generate certificates

----
[root@devopstesting linkerd]# step certificate create root.linkerd.cluster.local root.crt root.key \
>   --profile root-ca --no-password --insecure
Your certificate has been saved in root.crt.
Your private key has been saved in root.key.
----

**** To generate the issuer credentials using the trust anchor, run:
----
[root@devopstesting linkerd]# step certificate create identity.linkerd.cluster.local issuer.crt issuer.key \
>   --profile intermediate-ca --not-after 8760h --no-password --insecure \
>   --ca root.crt --ca-key root.key
Your certificate has been saved in issuer.crt.
Your private key has been saved in issuer.key.
----

**** An identity service in your cluster will use the certificate and key that you generated here to generate the certificates that each individual proxy uses. While we will be using the same issuer credentials on each cluster for this guide, it is a good idea to have separate ones for each cluster. Read through the certificate documentation for more details.

With a valid trust anchor and issuer credentials, we can install Linkerd on your west and east clusters now. will create lots things by below command

----
linkerd install \
  --identity-trust-anchors-file root.crt \
  --identity-issuer-certificate-file issuer.crt \
  --identity-issuer-key-file issuer.key \
  | tee \
    >(kubectl --context=west apply -f -) \
    >(kubectl --context=east apply -f -)
----

**** check things here by 

----
for ctx in west east; do
  echo "Checking cluster: ${ctx} .........\n"
  linkerd --context=${ctx} check || break
  echo "-------------\n"
done
----

**** To install the multicluster components on both west and east, you can run:

----
for ctx in west east; do
  echo "Installing on cluster: ${ctx} ........."
  linkerd --context=${ctx} multicluster install | \
    kubectl --context=${ctx} apply -f - || break
  echo "-------------\n"
done

Installing on cluster: west .........
namespace/linkerd-multicluster created
configmap/linkerd-gateway-config created
deployment.apps/linkerd-gateway created
service/linkerd-gateway created
serviceaccount/linkerd-gateway created
clusterrole.rbac.authorization.k8s.io/linkerd-service-mirror-remote-access-default created
serviceaccount/linkerd-service-mirror-remote-access-default created
clusterrolebinding.rbac.authorization.k8s.io/linkerd-service-mirror-remote-access-default created
customresourcedefinition.apiextensions.k8s.io/links.multicluster.linkerd.io created
-------------\n
Installing on cluster: east .........
namespace/linkerd-multicluster created
configmap/linkerd-gateway-config created
deployment.apps/linkerd-gateway created
service/linkerd-gateway created
serviceaccount/linkerd-gateway created
clusterrole.rbac.authorization.k8s.io/linkerd-service-mirror-remote-access-default created
serviceaccount/linkerd-service-mirror-remote-access-default created
clusterrolebinding.rbac.authorization.k8s.io/linkerd-service-mirror-remote-access-default created
customresourcedefinition.apiextensions.k8s.io/links.multicluster.linkerd.io created
-------------\n
----

**** Make sure gateway successfully deployed.

----
[root@devopstesting linkerd]# for ctx in west east; do
>   echo "Checking gateway on cluster: ${ctx} ........."
>   kubectl --context=${ctx} -n linkerd-multicluster \
>     rollout status deploy/linkerd-gateway || break
>   echo "-------------\n"
> done
Checking gateway on cluster: west .........
deployment "linkerd-gateway" successfully rolled out
-------------\n
Checking gateway on cluster: east .........
deployment "linkerd-gateway" successfully rolled out
-------------\n
----


**** Double check that the load balancer was able to allocate a public IP address by running:

----
[root@devopstesting linkerd]# for ctx in west east; do
>   printf "Checking cluster: ${ctx} ........."
>   while [ "$(kubectl --context=${ctx} -n linkerd-multicluster get service \
>     -o 'custom-columns=:.status.loadBalancer.ingress[0].ip' \
>     --no-headers)" = "<none>" ]; do
>       printf '.'
>       sleep 1
>   done
>   printf "\n"
> done
Checking cluster: west .........
Checking cluster: east .........

[root@devopstesting linkerd]# kubectl get svc -n linkerd-multicluster
NAME              TYPE           CLUSTER-IP     EXTERNAL-IP      PORT(S)                         AGE
linkerd-gateway   LoadBalancer   10.108.13.37   35.222.122.155   4143:32392/TCP,4181:30886/TCP   7m40s
----

**** To link the west cluster to the east one, run:

----
linkerd --context=east multicluster link --cluster-name east |
  kubectl --context=west apply -f -
  
secret/cluster-credentials-east created
link.multicluster.linkerd.io/east created
clusterrole.rbac.authorization.k8s.io/linkerd-service-mirror-access-local-resources-east created
clusterrolebinding.rbac.authorization.k8s.io/linkerd-service-mirror-access-local-resources-east created
role.rbac.authorization.k8s.io/linkerd-service-mirror-read-remote-creds-east created
rolebinding.rbac.authorization.k8s.io/linkerd-service-mirror-read-remote-creds-east created
serviceaccount/linkerd-service-mirror-east created
deployment.apps/linkerd-service-mirror-east created
service/probe-gateway-east created
----

