=== Create cluster in gcp

** Manually create gke cluster and rename cluster name as east, west
*** enable access for two cluster like
----
gcloud container clusters get-credentials devops3 --zone us-central1-c --project fr-dev-piiworker
----

*** rename
----
kubectl config rename-context gke_fr-dev-piiworker_us-central1-c_devops-2 east
kubectl config rename-context gke_fr-dev-piiworker_us-central1-c_devops3 west
----

**** We like to use the step CLI to generate these certificates. If you prefer openssl instead, feel free to use that! To generate the trust anchor with step
**** install step first
----
wget -O step-cli.tar.gz https://github.com/smallstep/cli/releases/download/v0.15.3/step_linux_0.15.3_amd64.tar.gz
tar -xf step-cli.tar.gz
sudo cp step_0.15.3/bin/step /usr/bin
----

**** generate certificates

----
[root@devopstesting linkerd]# step certificate create root.linkerd.cluster.local root.crt root.key \
>   --profile root-ca --no-password --insecure
Your certificate has been saved in root.crt.
Your private key has been saved in root.key.
----

**** To generate the issuer credentials using the trust anchor, run:
----
[root@devopstesting linkerd]# step certificate create identity.linkerd.cluster.local issuer.crt issuer.key \
>   --profile intermediate-ca --not-after 8760h --no-password --insecure \
>   --ca root.crt --ca-key root.key
Your certificate has been saved in issuer.crt.
Your private key has been saved in issuer.key.
----

**** An identity service in your cluster will use the certificate and key that you generated here to generate the certificates that each individual proxy uses. While we will be using the same issuer credentials on each cluster for this guide, it is a good idea to have separate ones for each cluster. Read through the certificate documentation for more details.

With a valid trust anchor and issuer credentials, we can install Linkerd on your west and east clusters now. will create lots things by below command

----
linkerd install \
  --identity-trust-anchors-file root.crt \
  --identity-issuer-certificate-file issuer.crt \
  --identity-issuer-key-file issuer.key \
  | tee \
    >(kubectl --context=west apply -f -) \
    >(kubectl --context=east apply -f -)
----

**** check things here by 

----
for ctx in west east; do
  echo "Checking cluster: ${ctx} .........\n"
  linkerd --context=${ctx} check || break
  echo "-------------\n"
done
----


